CREATE TABLE `USER` (
  `USER_ID` varchar(50) NOT NULL,
  `FIRST_NAME` varchar(80) DEFAULT NULL,
  `LAST_NAME` varchar(80) DEFAULT NULL,
  `EMAIL` varchar(500) DEFAULT NULL,
  `USER_NAME` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `LAST_UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LAST_UPDATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_AT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ;
